# Use an official Ubuntu image as the base image
FROM ubuntu:latest

# Install required dependencies
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
    wget \
    tar \
    net-tools \
    && rm -rf /var/lib/apt/lists/*

# Copy the XAMPP installer script to the image
COPY xampp.run /tmp/xampp-installer.run

# Make the installer script executable
RUN chmod +x /tmp/xampp-installer.run

# Run XAMPP installer in unattended mode
RUN /tmp/xampp-installer.run --mode unattended

# Replace extra httpd-xampp.conf
COPY container-configs/httpd-xampp.conf /opt/lampp/etc/extra/httpd-xampp.conf

# Replace default MySQL config
COPY container-configs/my.cnf /opt/lampp/etc/my.cnf

# Expose ports for Apache and MySQL
EXPOSE 80
EXPOSE 443
EXPOSE 3306

# Copy ATutor source code to /opt/lampp/htdocs
COPY ./ATutor /opt/lampp/htdocs/atutor

# Fix ATutor permissions
RUN mkdir /opt/lampp/htdocs/atutor/content
RUN chmod 2777 /opt/lampp/htdocs/atutor/content
RUN chmod a+rw /opt/lampp/htdocs/atutor/include/config.inc.php

# Start XAMPP
CMD ["/bin/bash", "-c", "/opt/lampp/lampp start && tail -f /dev/null"]
